#!/usr/bin/env python3
"""Transcribe Advantages & Disadvantages from GDD s45 into
`l5r_rules/advantages_catalog.py`, verbatim.

Each entry:  **Name [Category] (N pts) [source-tags]**  then an effect paragraph,
under an **ADVANTAGES:** or **DISADVANTAGES:** section. Entries marked REMOVED /
NOT IMPLEMENTED are skipped. Nothing is invented.

Usage (from discord_bot/):  python3 tools/extract_advantages.py [path-to-gdd]
"""

from __future__ import annotations

import os
import re
import sys

HEADER = re.compile(r"^\*\*(.+?)\*\*\s*$")
CATEGORIES = {"mental", "social", "physical", "mystical", "spiritual", "material"}


def _parse_header(inner: str) -> dict | None:
    # cost is the first (...) group
    cost_m = re.search(r"\(([^)]*)\)", inner)
    if not cost_m:
        return None
    cost_text = cost_m.group(1).strip()
    before = inner[: cost_m.start()]  # "Name [Category] "
    brackets = re.findall(r"\[([^\]]+)\]", before)
    category = ""
    tags = []
    for b in brackets:
        if b.lower() in CATEGORIES:
            category = b
        else:
            tags.append(b)
    # also collect source tags after the cost (e.g. [CR])
    tags += [b for b in re.findall(r"\[([^\]]+)\]", inner[cost_m.end():])]
    name = re.sub(r"\s*\[[^\]]+\]", "", before).strip()
    pts_m = re.search(r"(\d+)\s*pt", cost_text)
    points = int(pts_m.group(1)) if pts_m else None
    return {"name": name, "category": category, "points": points,
            "cost_text": cost_text, "tags": tags}


def main() -> None:
    gdd = sys.argv[1] if len(sys.argv) > 1 else os.path.join("..", "gdd")
    path = os.path.join(gdd, "s45_intro_advantages_disadvantages.md")
    lines = open(path, encoding="utf-8").read().split("\n")
    heads = [i for i, l in enumerate(lines) if HEADER.match(l)]
    catalog = []
    kind = "advantage"
    seen = set()
    for idx, start in enumerate(heads):
        inner = HEADER.match(lines[start]).group(1).strip()
        low = inner.lower()
        if low.rstrip(":") == "advantages":
            kind = "advantage"
            continue
        if low.rstrip(":") == "disadvantages":
            kind = "disadvantage"
            continue
        if inner.endswith(":"):  # some other section header
            continue
        if "removed" in low or "not implemented" in low:
            continue
        parsed = _parse_header(inner)
        if not parsed or not parsed["name"]:
            continue
        end = heads[idx + 1] if idx + 1 < len(heads) else len(lines)
        effect = "\n".join(l for l in lines[start + 1:end] if l.strip()).strip()
        key = (kind, parsed["name"].lower())
        if key in seen:
            continue
        seen.add(key)
        catalog.append({"kind": kind, **parsed, "effect": effect})

    catalog.sort(key=lambda r: (r["kind"], r["name"]))
    out = os.path.join("l5r_rules", "advantages_catalog.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write('"""AUTO-GENERATED by tools/extract_advantages.py — do not edit by hand.\n\n')
        fh.write(f"Advantages & Disadvantages, verbatim from GDD s45. {len(catalog)} entries.\n\"\"\"\n\n")
        fh.write("ADVANTAGES_DATA = [\n")
        for rec in catalog:
            fh.write("    " + repr(rec) + ",\n")
        fh.write("]\n")
    from collections import Counter
    print(f"Wrote {len(catalog)} entries to {out}")
    print(dict(Counter(r["kind"] for r in catalog)))


if __name__ == "__main__":
    main()
