#!/usr/bin/env python3
"""Transcribe every School and its Techniques from the GDD s29 markdown into
`l5r_rules/schools_catalog.py`, verbatim.

Each school in s29.*.md follows a rigid shape:

    **<Name> [tags]:**
    <description>
    - Benefit: +1 <Trait>
    - Skills: <list>
    - Honor: X | Outfit: <...>
    - Affinity/Deficiency: <...>        (shugenja)
    - Rank 1 — <Technique>: <effect>
    ... up to Rank 5
    - Technique — <Name>: <effect>      (advanced/alternate schools)

Only bold headers that have a "- Skills:" line are treated as schools (so section
headers like **BASIC SCHOOLS:** and the s29.15 framework prose are skipped). Clan
is inferred from the file. Nothing is invented — text is copied as-is.

Usage (from discord_bot/):  python3 tools/extract_schools.py [path-to-gdd]
"""

from __future__ import annotations

import os
import re
import sys

CLAN_BY_FILE = {
    "s29.1_": "Crab", "s29.2_": "Crane", "s29.3_": "Dragon", "s29.4_": "Lion",
    "s29.5_": "Phoenix", "s29.6_": "Scorpion", "s29.7_": "Unicorn",
    "s29.8_": "Imperial", "s29.9_": "Mantis", "s29.10_": "Mantis",
    "s29.11_": "Minor Clan", "s29.12_": "Ronin", "s29.13_": "Brotherhood",
    "s29.14_": "Miscellaneous",
}

HEADER = re.compile(r"^\*\*(.+?):\*\*\s*$")
RANK_TECH = re.compile(r"^-\s*Rank\s*(\d+)\s*[—–-]\s*(.+?):\s*(.+)$")
ALT_TECH = re.compile(r"^-\s*Technique\s*[—–-]\s*(.+?):\s*(.+)$")


def _clan_for(fname: str) -> str:
    for prefix, clan in CLAN_BY_FILE.items():
        if fname.startswith(prefix):
            return clan
    return ""


def _split_name(header_inner: str) -> tuple[str, list[str]]:
    tags = re.findall(r"\[([^\]]+)\]", header_inner)
    name = re.sub(r"\s*\[[^\]]+\]", "", header_inner).strip()
    return name, tags


def _parse_file(path: str, clan: str) -> list[dict]:
    lines = open(path, encoding="utf-8").read().split("\n")
    # header line indices
    heads = [i for i, l in enumerate(lines) if HEADER.match(l)]
    schools = []
    for idx, start in enumerate(heads):
        end = heads[idx + 1] if idx + 1 < len(heads) else len(lines)
        block = lines[start:end]
        name, tags = _split_name(HEADER.match(lines[start]).group(1))
        rec = {
            "name": name, "clan": clan, "keywords": tags,
            "benefit": "", "skills": "", "honor": "", "outfit": "",
            "affinity": "", "prereq": "", "techniques": [],
        }
        has_skills = False
        for line in block[1:]:
            s = line.strip()
            if not s.startswith("-"):
                continue
            m = RANK_TECH.match(s)
            if m:
                rec["techniques"].append({"rank": int(m.group(1)), "name": m.group(2).strip(), "effect": m.group(3).strip()})
                continue
            m = ALT_TECH.match(s)
            if m:
                rec["techniques"].append({"rank": 0, "name": m.group(1).strip(), "effect": m.group(2).strip()})
                continue
            body = s[1:].strip()
            low = body.lower()
            if low.startswith("benefit:"):
                rec["benefit"] = body.split(":", 1)[1].strip()
            elif low.startswith("skills:"):
                rec["skills"] = body.split(":", 1)[1].strip()
                has_skills = True
            elif low.startswith("honor:"):
                rest = body.split(":", 1)[1].strip()
                if "|" in rest:
                    honor_part, outfit_part = rest.split("|", 1)
                    rec["honor"] = honor_part.strip()
                    rec["outfit"] = outfit_part.split(":", 1)[-1].strip()
                else:
                    rec["honor"] = rest
            elif low.startswith("affinity"):
                rec["affinity"] = body.split(":", 1)[1].strip()
            elif low.startswith("replaces:") or low.startswith("requires:"):
                rec["prereq"] = (rec["prereq"] + " " + body).strip()
        if has_skills:
            rec["techniques"].sort(key=lambda t: (t["rank"] if t["rank"] else 99))
            schools.append(rec)
    return schools


def main() -> None:
    gdd = sys.argv[1] if len(sys.argv) > 1 else os.path.join("..", "gdd")
    files = sorted(f for f in os.listdir(gdd) if re.match(r"s29\.\d+_", f) and f.endswith(".md"))
    catalog: list[dict] = []
    seen: set[str] = set()
    for fname in files:
        clan = _clan_for(fname)
        for rec in _parse_file(os.path.join(gdd, fname), clan):
            key = rec["name"].lower()
            if key in seen:
                continue
            seen.add(key)
            catalog.append(rec)
    catalog.sort(key=lambda r: (r["clan"], r["name"]))
    out = os.path.join("l5r_rules", "schools_catalog.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write('"""AUTO-GENERATED by tools/extract_schools.py — do not edit by hand.\n\n')
        fh.write("Schools and their Techniques, transcribed verbatim from the GDD s29\n")
        fh.write(f"markdown. {len(catalog)} schools. Re-run the extractor to refresh.\n\"\"\"\n\n")
        fh.write("SCHOOLS_DATA = [\n")
        for rec in catalog:
            fh.write("    " + repr(rec) + ",\n")
        fh.write("]\n")
    tech_total = sum(len(r["techniques"]) for r in catalog)
    print(f"Wrote {len(catalog)} schools ({tech_total} techniques) to {out}")
    # quick clan histogram
    from collections import Counter
    print(dict(Counter(r["clan"] for r in catalog)))


if __name__ == "__main__":
    main()
