#!/usr/bin/env python3
"""Transcribe Kata (GDD s30) and Kiho (GDD s38) into
`l5r_rules/kata_catalog.py` and `l5r_rules/kiho_catalog.py`, verbatim.

Kata entry:  **Name**  /  - Ring/Mastery: Air 3 | Schools: ...  /  - Effect: ...
Kiho entry:  **Name**  /  - Air 3 (Atemi)?  /  - Type: Internal  /  <effect>

Section headers (**AIR KATA:**, **AIR KIHO:**) end in ':' and are skipped.
Nothing is invented.

Usage (from discord_bot/):  python3 tools/extract_kata_kiho.py [path-to-gdd]
"""

from __future__ import annotations

import os
import re
import sys

HEADER = re.compile(r"^\*\*(.+?)\*\*\s*$")
RM = re.compile(r"([A-Za-z]+)\s+(\d+)")


def _blocks(path: str):
    lines = open(path, encoding="utf-8").read().split("\n")
    heads = [i for i, l in enumerate(lines) if HEADER.match(l)]
    for idx, start in enumerate(heads):
        inner = HEADER.match(lines[start]).group(1).strip()
        if inner.endswith(":"):  # section header
            continue
        end = heads[idx + 1] if idx + 1 < len(heads) else len(lines)
        yield inner, lines[start + 1:end]


def parse_kata(path: str) -> list[dict]:
    out = []
    for name, block in _blocks(path):
        element = mastery = None
        schools = effect = ""
        for l in block:
            s = l.strip()
            if s.lower().startswith("- ring/mastery:") or s.lower().startswith("-ring/mastery:"):
                seg = s.split(":", 1)[1]
                rm_part = seg.split("|")[0]
                m = RM.search(rm_part)
                if m:
                    element, mastery = m.group(1), int(m.group(2))
                if "schools:" in s.lower():
                    schools = s.lower().split("schools:", 1)[1].strip()
                    schools = seg.split("Schools:", 1)[1].strip() if "Schools:" in seg else schools
            elif s.lower().startswith("- effect:"):
                effect = s.split(":", 1)[1].strip()
        if element and mastery:
            out.append({"name": name, "element": element, "mastery": mastery,
                        "schools": schools, "effect": effect})
    return out


def parse_kiho(path: str) -> list[dict]:
    out = []
    for name, block in _blocks(path):
        element = mastery = None
        atemi = False
        ktype = ""
        effect_lines = []
        for l in block:
            s = l.strip()
            if s.startswith("-"):
                body = s[1:].strip()
                low = body.lower()
                if low.startswith("type:"):
                    ktype = body.split(":", 1)[1].strip()
                    continue
                m = RM.match(body)
                if m and element is None:
                    element, mastery = m.group(1), int(m.group(2))
                    atemi = "atemi" in low
                    continue
                # any other bullet -> treat as effect text
                effect_lines.append(body)
            elif s:
                effect_lines.append(s)
        if element and mastery:
            out.append({"name": name, "element": element, "mastery": mastery,
                        "atemi": atemi, "type": ktype, "effect": " ".join(effect_lines).strip()})
    return out


def _write(path: str, var: str, data: list[dict], label: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f'"""AUTO-GENERATED by tools/extract_kata_kiho.py — do not edit by hand.\n\n')
        fh.write(f"{label}, verbatim from the GDD. {len(data)} entries.\n\"\"\"\n\n")
        fh.write(f"{var} = [\n")
        for rec in data:
            fh.write("    " + repr(rec) + ",\n")
        fh.write("]\n")


def main() -> None:
    gdd = sys.argv[1] if len(sys.argv) > 1 else os.path.join("..", "gdd")
    kata = parse_kata(os.path.join(gdd, "s30_katas.md"))
    kiho = parse_kiho(os.path.join(gdd, "s38_kiho.md"))
    kata.sort(key=lambda r: (r["element"], r["mastery"], r["name"]))
    kiho.sort(key=lambda r: (r["element"], r["mastery"], r["name"]))
    _write(os.path.join("l5r_rules", "kata_catalog.py"), "KATA_DATA", kata, "Kata (GDD s30)")
    _write(os.path.join("l5r_rules", "kiho_catalog.py"), "KIHO_DATA", kiho, "Kiho (GDD s38)")
    print(f"Wrote {len(kata)} kata and {len(kiho)} kiho.")


if __name__ == "__main__":
    main()
