#!/usr/bin/env python3
"""Transcribe every spell from the GDD s32–s37 markdown into
`l5r_rules/spells_catalog.py`, verbatim.

Two layouts are handled:
  - Universal (s32):  **Name [tags]**  /  - Ring/Mastery: All 1 | Range: .. | Area of Effect: .. | Duration: .. | Raises: ..
  - Element (s33-37): **Name [tags]**  /  - Air 1 (Battle) | Range: .. | Area: .. | Duration: .. | Raises: ..

A bold header that is NOT a section header (does not end in ':') and is followed
by a stat line (a "- …|…" line) is a spell. Element and Mastery Level are read
from the stat line's first segment. Nothing is invented.

Usage (from discord_bot/):  python3 tools/extract_spells.py [path-to-gdd]
"""

from __future__ import annotations

import os
import re
import sys

HEADER = re.compile(r"^\*\*(.+?)\*\*\s*$")
STATLINE = re.compile(r"^-\s*(.+\|.+)$")
# first segment -> element, mastery, optional keyword: "All 1", "Air 1 (Battle)", "Any non-Void 2"
ELEM = re.compile(r"^(.*?)(\d+)\s*(?:\(([^)]+)\))?\s*$")


def _split_name(inner: str) -> tuple[str, list[str]]:
    tags = re.findall(r"\[([^\]]+)\]", inner)
    name = re.sub(r"\s*\[[^\]]+\]", "", inner).strip()
    return name, tags


def _parse_statline(seg_str: str) -> dict | None:
    segs = [s.strip() for s in seg_str.split("|")]
    first = segs[0]
    if first.lower().startswith("ring/mastery:"):
        first = first.split(":", 1)[1].strip()
    m = ELEM.match(first)
    if not m:
        return None
    rec = {
        "element": m.group(1).strip(),
        "mastery": int(m.group(2)),
        "keyword": (m.group(3) or "").strip(),
        "range": "", "area": "", "duration": "", "raises": "",
    }
    for seg in segs[1:]:
        if ":" not in seg:
            continue
        key, val = seg.split(":", 1)
        key = key.strip().lower()
        val = val.strip()
        if key.startswith("range"):
            rec["range"] = val
        elif key.startswith("area"):
            rec["area"] = val
        elif key.startswith("duration"):
            rec["duration"] = val
        elif key.startswith("raises"):
            rec["raises"] = val
    return rec


def _parse_file(path: str) -> list[dict]:
    lines = open(path, encoding="utf-8").read().split("\n")
    heads = [i for i, l in enumerate(lines) if HEADER.match(l)]
    spells = []
    for idx, start in enumerate(heads):
        end = heads[idx + 1] if idx + 1 < len(heads) else len(lines)
        inner = HEADER.match(lines[start]).group(1)
        if inner.rstrip().endswith(":"):  # section header (MASTERY LEVEL 1:, etc.)
            continue
        block = lines[start + 1:end]
        stat_idx = next((j for j, l in enumerate(block) if STATLINE.match(l)), None)
        if stat_idx is None:
            continue
        stats = _parse_statline(STATLINE.match(block[stat_idx]).group(1))
        if stats is None:
            continue
        name, tags = _split_name(inner)
        effect = "\n".join(l for l in block[stat_idx + 1:] if l.strip()).strip()
        rec = {"name": name, "tags": tags, **stats, "effect": effect}
        spells.append(rec)
    return spells


def main() -> None:
    gdd = sys.argv[1] if len(sys.argv) > 1 else os.path.join("..", "gdd")
    files = sorted(f for f in os.listdir(gdd) if re.match(r"s3[2-7]_", f) and f.endswith(".md"))
    catalog: list[dict] = []
    seen: set[str] = set()
    for fname in files:
        for rec in _parse_file(os.path.join(gdd, fname)):
            key = rec["name"].lower()
            if key in seen:
                continue
            seen.add(key)
            catalog.append(rec)
    catalog.sort(key=lambda r: (r["element"], r["mastery"], r["name"]))
    out = os.path.join("l5r_rules", "spells_catalog.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write('"""AUTO-GENERATED by tools/extract_spells.py — do not edit by hand.\n\n')
        fh.write(f"Spells transcribed verbatim from the GDD s32-s37. {len(catalog)} spells.\n\"\"\"\n\n")
        fh.write("SPELLS_DATA = [\n")
        for rec in catalog:
            fh.write("    " + repr(rec) + ",\n")
        fh.write("]\n")
    from collections import Counter
    print(f"Wrote {len(catalog)} spells to {out}")
    print(dict(Counter(r["element"] for r in catalog)))


if __name__ == "__main__":
    main()
